# 20 NumPy

**NumPy** - Numerical Python Library

**NumPy** is the fundamental package for scientific computing in Python. It provides:
- High-performance multidimensional array objects (ndarray)
- Tools for working with arrays and mathematical operations
- Linear algebra, Fourier transform, and random number capabilities

**Key Use Cases:**
1. Scientific Computing: Mathematical operations on large datasets
2. Data Analysis: Foundation for pandas and data manipulation
3. Machine Learning: Base array structure for ML libraries (scikit-learn, TensorFlow)
4. Image Processing: Representing and manipulating image data
5. Signal Processing: Audio and signal analysis
6. Linear Algebra: Matrix operations and transformations
7. Statistical Analysis: Statistical computations and probability distributions
8. Simulation: Monte Carlo simulations and numerical experiments

Performance: NumPy is written in C, making it significantly faster than pure Python loops
for numerical operations through vectorization.

## Import NumPy

In [5]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.3.4


## Creating Arrays

In [6]:
# From list
arr1 = np.array([1, 2, 3, 4, 5])
print("From list:", arr1)

# 2D array
arr2 = np.array([[1,2], [3,4]])
print("2D array:", arr2)

From list: [1 2 3 4 5]
2D array: [[1 2]
 [3 4]]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Empty: [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
Arange: [0 1 2 3 4 5 6 7 8 9]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Random: [[0.34581976 0.18113034 0.20659641]
 [0.65404619 0.31263189 0.98964179]
 [0.9737041  0.41617088 0.64999633]]


In [ ]:
# Zeros, ones, empty
zeros = np.zeros((3,3))
ones = np.ones((2,4))
empty = np.empty((2,2))
print("Zeros:", zeros)
print("Ones:", ones)
print("Empty:", empty)

In [ ]:
# Range
range_arr = np.arange(10)
print("Arange:", range_arr)

In [ ]:
# Linspace
lin = np.linspace(0, 1, 5)
print("Linspace:", lin)

In [ ]:
# Random
rand = np.random.rand(3,3)
print("Random:", rand)

## Array Attributes and Properties

In [7]:
arr = np.array([[1,2,3], [4,5,6]])
print("Array:", arr)
print("Shape:", arr.shape)
print("Dtype:", arr.dtype)
print("Ndim:", arr.ndim)
print("Size:", arr.size)
print("Itemsize:", arr.itemsize)

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dtype: int64
Ndim: 2
Size: 6
Itemsize: 8


## Indexing and Slicing

In [8]:
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("Index 0:", arr[0])
print("Slice 1:3:", arr[1:3])

# 2D
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("2D Array:", arr2d)
print("Element [1,2]:", arr2d[1,2])
print("Row 0:", arr2d[0])
print("Column 1:", arr2d[:,1])

# Boolean indexing
print("Boolean indexing:", arr[arr > 25])

Array: [10 20 30 40 50]
Index 0: 10
Slice 1:3: [20 30]
2D Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element [1,2]: 6
Row 0: [1 2 3]
Column 1: [2 5 8]
Boolean indexing: [30 40 50]


## Array Operations

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a:", a)
print("b:", b)
print("a + b:", a + b)
print("a * b:", a * b)
print("a ** 2:", a ** 2)
print("np.sin(a):", np.sin(a))

a: [1 2 3]
b: [4 5 6]
a + b: [5 7 9]
a * b: [ 4 10 18]
a ** 2: [1 4 9]
np.sin(a): [0.84147098 0.90929743 0.14112001]


## Broadcasting

In [10]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([10, 20, 30])
print("a:", a)
print("b:", b)
print("a + b:", a + b)

a: [[1 2 3]
 [4 5 6]]
b: [10 20 30]
a + b: [[11 22 33]
 [14 25 36]]


## Reshaping and Transposing

In [11]:
arr = np.arange(12)
print("1D:", arr)
reshaped = arr.reshape(3,4)
print("Reshaped 3x4:", reshaped)
print("Transpose:", reshaped.T)
print("Flatten:", reshaped.flatten())
print("Ravel:", reshaped.ravel())

1D: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 3x4: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## Concatenation and Splitting

In [12]:
a = np.array([1,2])
b = np.array([3,4])
print("a:", a)
print("b:", b)
print("Concatenate:", np.concatenate((a,b)))
print("Vstack:", np.vstack((a,b)))
print("Hstack:", np.hstack((a,b)))

arr = np.arange(10)
print("Array:", arr)
print("Split into 2:", np.split(arr, 2))

a: [1 2]
b: [3 4]
Concatenate: [1 2 3 4]
Vstack: [[1 2]
 [3 4]]
Hstack: [1 2 3 4]
Array: [0 1 2 3 4 5 6 7 8 9]
Split into 2: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


## Mathematical Functions

In [13]:
arr = np.array([1,2,3,4,5])
print("Array:", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Std:", np.std(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Sin:", np.sin(arr))

Array: [1 2 3 4 5]
Sum: 15
Mean: 3.0
Std: 1.4142135623730951
Min: 1
Max: 5
Sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


## Linear Algebra Operations

In [14]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print("a:", a)
print("b:", b)
print("Dot product:", np.dot(a,b))
print("Matrix multiply:", a @ b)
print("Transpose a:", a.T)
print("Inverse a:", np.linalg.inv(a))
print("Eigenvalues:", np.linalg.eigvals(a))

a: [[1 2]
 [3 4]]
b: [[5 6]
 [7 8]]
Dot product: [[19 22]
 [43 50]]
Matrix multiply: [[19 22]
 [43 50]]
Transpose a: [[1 3]
 [2 4]]
Inverse a: [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]


## Random Number Generation

In [15]:
np.random.seed(42)
print("Random int:", np.random.randint(0,10,5))
print("Normal:", np.random.normal(0,1,5))
print("Choice:", np.random.choice([1,2,3,4,5], 3))
print("Rand:", np.random.rand(3))

Random int: [6 3 7 4 6]
Normal: [-0.91682684 -0.12414718 -2.01096289 -0.49280342  0.39257975]
Choice: [5 2 4]
Rand: [9.38552709e-01 7.78765841e-04 9.92211559e-01]


## File I/O with Arrays

In [16]:
arr = np.array([1,2,3,4,5])
np.save('temp.npy', arr)
loaded = np.load('temp.npy')
print("Saved and loaded:", loaded)

np.savetxt('temp.txt', arr)
loaded_txt = np.loadtxt('temp.txt')
print("Saved txt and loaded:", loaded_txt)

Saved and loaded: [1 2 3 4 5]
Saved txt and loaded: [1. 2. 3. 4. 5.]


## Performance Tips

NumPy provides efficient operations through vectorization, avoiding explicit loops for better performance. Use built-in functions and operations instead of Python loops.

In [17]:
import time

arr = np.arange(1000000)

# Vectorized
start = time.time()
result = arr * 2
end = time.time()
print("Vectorized time:", end - start)

# Loop
start = time.time()
result2 = []
for x in arr:
    result2.append(x * 2)
end = time.time()
print("Loop time:", end - start)

Vectorized time: 0.0010919570922851562
Loop time: 0.07499289512634277
Loop time: 0.07499289512634277


## Cleanup

In [18]:
import os

for f in ["temp.npy", "temp.txt"]:
    if os.path.exists(f):
        os.remove(f)
        print(f"Removed: {f}")

print("\nCleanup complete!")

Removed: temp.npy
Removed: temp.txt

Cleanup complete!
